### ISSUE TITLE
Issue 7: For Milestone 4 Hyper-Parameter Tuning and Ensembles (9-11)

### ISSUE THREAD

**Issue by Josh-chief** [Josh-chief/TEAM-C.I-Rash-Hour#6]
- [x] Random/Grid/Manual Search
- [x] Bagging/Boosting/Stacking Ensembles (if applicable)

**Comment by bfg-ug** [comment]
Doesn't apply for a regression

**Comment by Josh-chief** [comment]
7th issue done
